name: documentation
on:
  push:
    branches:
      - 'main'
      - 'master'
jobs:
  Push-Docs-To-Website:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install Python dependencies
        run: pip install jinja2 typedecorator markdown
      - name: Compile documentation
        run: |
          cd ${{ github.workspace }}/docs/
          python -m ForgeDoc
      - name: Create pull request
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/create-pr.sh"
          "${GITHUB_WORKSPACE}/.github/workflows/create-pr.sh"
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          SOURCE_FOLDER: '${{ github.workspace }}/docs/build'
          DESTINATION_REPO: 'forgeluaengine/forgeluaengine.github.io'
          DESTINATION_FOLDER: ''
          DESTINATION_BASE_BRANCH: 'master'
          DESTINATION_HEAD_BRANCH: 'master'
          PR_TITLE: 'Update Forge documentation'
          COMMIT_MESSAGE: 'Update Forge documentation'
          USER_EMAIL: 'foe@forgetech.com'
          USER_NAME: 'Foereaper'
